"""add requirement id to agent run records

Revision ID: 07b5eb1f7540
Revises: d68e72242bb6
Create Date: 2026-07-26 15:08:23.890344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07b5eb1f7540'
down_revision: Union[str, Sequence[str], None] = 'd68e72242bb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_run_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requirement_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_agent_run_records_requirement_id'), ['requirement_id'], unique=False)
        batch_op.create_foreign_key(
            "fk_agent_run_records_requirement_id_requirements",
            "requirements",
            ["requirement_id"],
            ["id"],
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_run_records', schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_agent_run_records_requirement_id_requirements",
            type_="foreignkey",
        )
        batch_op.drop_index(batch_op.f('ix_agent_run_records_requirement_id'))
        batch_op.drop_column('requirement_id')

    # ### end Alembic commands ###
