"""add agent run records

Revision ID: d68e72242bb6
Revises: ef576cf07c5a
Create Date: 2026-07-24 16:37:41.229243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd68e72242bb6'
down_revision: Union[str, Sequence[str], None] = 'ef576cf07c5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_run_records',
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('step_count', sa.Integer(), nullable=False),
    sa.Column('max_steps', sa.Integer(), nullable=False),
    sa.Column('state_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('run_id')
    )
    with op.batch_alter_table('agent_run_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_run_records_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_run_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_run_records_status'))

    op.drop_table('agent_run_records')
    # ### end Alembic commands ###
