"""add knowledge references to analyses

Revision ID: ef576cf07c5a
Revises: 59fe1c5fe475
Create Date: 2026-07-21 22:17:06.607263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef576cf07c5a'
down_revision: Union[str, Sequence[str], None] = '59fe1c5fe475'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requirement_analyses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('knowledge_references', sa.JSON(), server_default='[]', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requirement_analyses', schema=None) as batch_op:
        batch_op.drop_column('knowledge_references')

    # ### end Alembic commands ###
