"""create initial schema

Revision ID: fb5144fe1c22
Revises: 
Create Date: 2026-07-20 15:31:32.985989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb5144fe1c22'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('requirements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_requirements_id'), ['id'], unique=False)

    op.create_table('requirement_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requirement_id', sa.Integer(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('planned_tools', sa.JSON(), nullable=False),
    sa.Column('current_priority', sa.Integer(), nullable=True),
    sa.Column('suggested_priority', sa.Integer(), nullable=True),
    sa.Column('priority_consistent', sa.Boolean(), nullable=True),
    sa.Column('issues', sa.JSON(), nullable=False),
    sa.Column('tool_results', sa.JSON(), nullable=False),
    sa.Column('final_report', sa.Text(), nullable=False),
    sa.Column('llm_fallback_used', sa.Boolean(), nullable=False),
    sa.Column('llm_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('requirement_analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_requirement_analyses_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_requirement_analyses_requirement_id'), ['requirement_id'], unique=False)

    op.create_table('requirement_analysis_cache',
    sa.Column('requirement_id', sa.Integer(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['requirement_analyses.id'], ),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ),
    sa.PrimaryKeyConstraint('requirement_id')
    )
    with op.batch_alter_table('requirement_analysis_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_requirement_analysis_cache_fingerprint'), ['fingerprint'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requirement_analysis_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_requirement_analysis_cache_fingerprint'))

    op.drop_table('requirement_analysis_cache')
    with op.batch_alter_table('requirement_analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_requirement_analyses_requirement_id'))
        batch_op.drop_index(batch_op.f('ix_requirement_analyses_id'))

    op.drop_table('requirement_analyses')
    with op.batch_alter_table('requirements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_requirements_id'))

    op.drop_table('requirements')
    # ### end Alembic commands ###
